### ISSUE TITLE
Addnodes

### ISSUE THREAD

**Issue by le2Ks** [BigRock88/fucucoin#1]
Any addnodes? Cannot get the wallet connected to the network

**Comment by BigRock88** [comment]
Hi Tyler. We haven't officially launched yet. I am working on things today and hope to have everything ready to go in the next day or so.  I will let you know when. Thanks

**Comment by le2Ks** [comment]
Hello, oh ok. Thanks for answering! 

Best'

EDIT: do you also have a website or discord/telegram group for your project?

**Comment by BigRock88** [comment]
Just finalising everything. Hope to launch later this week. How did you come across this project?

**Comment by le2Ks** [comment]
Oh ok sounds good. Saw the project on Github by chance.
